language: python

sudo: required

services:
  - docker

before_install:
  - docker build -t albert1989/django-heroku-travis -f Dockerfile.dev .

script:
  - docker run albert1989/django-heroku-travis pytest

deploy:
  provider: heroku
  app: django-heroku-travis
  api_key: $HEROKU_AUTH_TOKEN